### ISSUE TITLE
Multiple URI parameters not recognized

### ISSUE THREAD

**Issue by urbanusjam** [nidi3/raml-tester#81]
Does the raml-tester support multiple URI parameters for the same resource? I have the following endpoint that defines two URI parameters in its path:

```
/Messages:
  /{MessageId}{mediaTypeExtension}:
    uriParameters:
      MessageSid:
        type: string
        required: true
      mediaTypeExtension:
        enum: [ .json, .xml ]
        type: string
        required: false
```

However, the validation fails with the error below:

```
Resource '/Messages/12345.json' is not defined
```

If I remove the {mediaTypeExtension}, the validation passes.
